apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hub
spec:
  serviceName: hub
  selector:
    matchLabels:
      io.kompose.service: hub
  template:
    metadata:
      labels:
        io.kompose.service: hub
    spec:
      securityContext:
        fsGroup: 13001
      containers:
        - image: jetbrains/hub:2021.1.14194
          name: hub
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/hub/data
              name: hub-data
            - mountPath: /opt/hub/conf
              name: hub-conf
            - mountPath: /opt/hub/logs
              name: hub-logs
            - mountPath: /opt/hub/backups
              name: hub-backups
      volumes:
        - name: hub-data
          emptyDir: { }
        - name: hub-conf
          emptyDir: { }
        - name: hub-logs
          emptyDir: { }
        - name: hub-backups
          emptyDir: { }