services:
  datalore:
    ports:
      - "8081:8081"
      - "5050:5050"
      - "4060:4060"
    environment:
      EXTERNAL_PASSWORD: "changemeExternal"
      EXTERNAL_SERVER_URL: "http://external-server:8111"
      COMPUTATION_HOST: "changeme"
      AGENT_MANAGER_HOST: "changeme"
      AGENT_DISK_HOST: "changeme"
  external-server:
    image: jetbrains/datalore-external:2023.1
    ports:
      - "8111:8111"
    expose: [ "8111" ]
    networks:
      - datalore-backend-network
    volumes:
      - "external-storage:/data/volume"
    environment:
      DB_PASSWORD: "changeme"
      EXTERNAL_PASSWORD: "changemeExternal"
volumes:
  external-storage: { }
