apiVersion: batch/v1
kind: Job
metadata:
  name: connection-check
  labels:
    datalore-databases: connection-check
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        datalore-databases: connection-check
    spec:
      restartPolicy: Never
      containers:
        - name: introspection
          image: jetbrains/datalore-connection-checker:2022.1.2
          securityContext:
            runAsUser: 5000