apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datalore-on-premise
spec:
  template:
    spec:
      containers:
        - name: datalore
          image: jetbrains/datalore-server:v0.2.1
        - name: postgres
          image: jetbrains/datalore-postgres:v0.2.1
