apiVersion: batch/v1
kind: Job
metadata:
  name: introspection
  labels:
    datalore-databases: introspection
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 1200
  ttlSecondsAfterFinished: 6000
  template:
    metadata:
      labels:
        datalore-databases: introspection
    spec:
      restartPolicy: Never
      containers:
        - name: introspection
          image: jetbrains/datalore-introspection:2021.3.4