channels: # should correspond with all .condarc files in repo & install.sh
  - jetbrains
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pandas==1.3.4

  # libraries needed by evaluator
  - ipykernel=5.5.3
  - ipython_genutils==0.2.0

  # https://github.com/ipython/ipython/issues/12740
  - jedi=0.17.2
  - pip=21.3.1
  - pip:
      - lets-plot==2.3.0