apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datalore.fullname" . }}-agents-config
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  agents-config.yaml: |-
{{- if .Values.agentsConfig }}
{{- tpl (toYaml .Values.agentsConfig) . | nindent 4 }}
{{- else }}
    k8s:
      namespace: {{ .Release.Namespace }}
      instances:
        - id: k8s-datalore-agent
          label: "K8s Local"
          description: "Local K8s instance"
          features:
            - "1 CPU cores"
            - "2 GB RAM"
          minAllowed: 1
          maxAllowed: 1
          numCPUs: 1
          cpuMemoryText: "2 GB"
          numGPUs: 0
          gpuMemoryText: ""
          default: true
          yaml:
            apiVersion: v1
            kind: Pod
            metadata:
              name: k8s-agent
              labels:
                podType: dataloreKubernetesAgent
            spec:
              enableServiceLinks: false
              containers:
                - name: agent
                  image: jetbrains/datalore-agent:{{ .Values.dataloreVersion | default .Chart.AppVersion }}
                  securityContext:
                    privileged: true
                  env:
                    - name: MAX_HEAP_SIZE
                      value: 512m
                  volumeMounts:
                    - mountPath: /etc/datalore/logback-config
                      name: logback-config
                  resources:
                    limits:
                      cpu: "1"
                      memory: "2048Mi"
                    requests:
                      cpu: "200m"
                      memory: "2048Mi"
              volumes:
                - name: logback-config
                  configMap:
                    name: {{ include "datalore.fullname" . }}-logback-config
{{- end }}
