apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datalore.fullname" . }}-databases-config
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  connection_checker.yaml: |-
{{- if .Values.connectionChecker }}
{{- tpl (toYaml .Values.connectionChecker) . | nindent 4 }}
{{- else }}
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: connection-check
      labels:
        datalore-databases: connection-check
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 120
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            datalore-databases: connection-check
        spec:
          restartPolicy: Never
          containers:
            - name: connection-check
              image: {{ .Values.databaseCommandImage.repository }}:{{ .Values.dataloreVersion | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.databaseCommandImage.pullPolicy }}
              securityContext:
                runAsUser: 5000
{{- end }}
  introspection.yaml: |-
{{- if .Values.introspection }}
{{- tpl (toYaml .Values.introspection) . | nindent 4 }}
{{- else }}
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: introspection
      labels:
        datalore-databases: introspection
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 1200
      ttlSecondsAfterFinished: 6000
      template:
        metadata:
          labels:
            datalore-databases: introspection
        spec:
          restartPolicy: Never
          containers:
            - name: introspection
              image: {{ .Values.databaseCommandImage.repository }}:{{ .Values.dataloreVersion | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.databaseCommandImage.pullPolicy }}
              securityContext:
                runAsUser: 5000
{{- end }}
  namespaces_loader.yaml: |-
{{- if .Values.namespacesLoader }}
{{- tpl (toYaml .Values.namespacesLoader) . | nindent 4 }}
{{- else }}
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: namespaces-loader
      labels:
        datalore-databases: namespaces-loader
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 120
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            datalore-databases: namespaces-loader
        spec:
          restartPolicy: Never
          containers:
            - name: connection-check
              image: {{ .Values.databaseCommandImage.repository }}:{{ .Values.dataloreVersion | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.databaseCommandImage.pullPolicy }}
              securityContext:
                runAsUser: 5000
{{- end }}
  sql_session.yaml: |+
{{- if .Values.sqlSession }}
{{- tpl (toYaml .Values.sqlSession) . | nindent 4 }}
{{- else }}
    apiVersion: v1
    kind: Service
    metadata:
      name: sql-session-service
    spec:
      type: ClusterIP
      ports:
        - port: 8087
          targetPort: 8087
      selector:
        app: sql-session
    ---
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: sql-session
      labels:
        app: sql-session
        datalore-databases: sql-session
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 600
      template:
        metadata:
          labels:
            datalore-databases: sql-session
        spec:
          restartPolicy: Never
          containers:
            - name: sql-session
              image: {{ .Values.sqlSessionImage.repository }}:{{ .Values.dataloreVersion | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.sqlSessionImage.pullPolicy }}
{{- end }}