apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-db
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  ROOT_PASSWORD: {{ .Values.dbRootPassword | b64enc }}
