apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datalore.fullname" . }}-envs-config
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
{{- if .Values.customEnvs }}
{{- toYaml .Values.customEnvs | nindent 2 }}
{{- else }}
  environment_minimal.yml: |-
    #
    # Minimum set of libs required by kernels and for basic data-science tasks
    # Created to provide minimum conda environment for Kubernetes agents
    #
    channels: # should correspond with all .condarc files in repo & install.sh
      - jetbrains
      - jetbrains-dev
      - fastai
      - pytorch
      - conda-forge
      - defaults
    dependencies:
      - python=3.8.12

      # libraries needed by evaluator
      - ipykernel=5.5.3
      - ipython_genutils=0.2.0

      # https://github.com/ipython/ipython/issues/12740
      - jedi=0.17.2

      # Data Science libraries
      - matplotlib-base=3.3.4
      - numpy=1.19.5
      - pandas=1.3.4

      - pip=21.3.1
      - boto3=1.17.7
      - pip:
        - lets-plot==2.2.0
  requirements_minimal.txt: |-
    boto3==1.17.7
    ipykernel==5.5.3
    ipython_genutils==0.2.0
    jedi==0.17.2
    kotlin-jupyter-kernel==0.10.3.20
    lets-plot==2.2.0
    matplotlib==3.3.4
    numpy==1.19.5
    scikit-image==0.18.3
    scikit-learn==1.0
    scipy==1.7.1
    seaborn==0.11.2
    pandas==1.3.4
    pandas-datareader==0.10.0
    pip==21.3.1
    plotly==5.3.1
{{- end }}