{{- if .Values.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-external
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  EXTERNAL_PASSWORD: {{ .Values.external.token | b64enc }}
{{- end }}
