{{- if .Values.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-external-license
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  license.keys: |
   {{ .Values.external.license | b64enc }}
{{- end }}
