{{- if .Values.logbackConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datalore.fullname" . }}-logback-config
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  logback.xml: |-
{{- .Values.logbackConfig | nindent 4 }}
{{- end }}
