apiVersion: v1
kind: Service
metadata:
  name: {{ include "datalore.fullname" . }}
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.httpInternalPort }}
      targetPort: http-internal
      protocol: TCP
      name:  http-internal
    - port: {{ .Values.agentsManagerPort }}
      targetPort: agents-manager
      protocol: TCP
      name: agents-manager
    - port: {{ .Values.computationPort }}
      targetPort: computation
      protocol: TCP
      name: computation
  selector:
    {{- include "datalore.selectorLabels" . | nindent 4 }}
