apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-user-env
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
stringData:
  DATABASES_K8S_NAMESPACE: {{ .Release.Namespace }}
  {{- range $k, $v := .Values.dataloreEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
