apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-user-env
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
stringData:
  user_secret_env.sh: |
  {{- range $k, $v := .Values.dataloreEnv }}
    export {{ $k }}={{ $v | quote }}
  {{- end }}
