apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-user-env
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  DATABASES_K8S_NAMESPACE: {{ .Release.Namespace | b64enc }}
  GIT_TASK_K8S_NAMESPACE: {{ .Release.Namespace | b64enc }}
  {{- range $k, $v := .Values.dataloreEnv }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
