apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datalore.fullname" . }}-user-env
  labels:
    {{- include "datalore.labels" . | nindent 4 }}
data:
  user_secret_env.sh: {{ .Values.dataloreEnv | b64enc }}
