apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datalore-on-premise
spec:
  template:
    spec:
      volumes:
        - name: storage
          emptyDir: { }
        - name: postgres-data
          emptyDir: { }
