apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hub
  name: hub
spec:
  ports:
    - port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: hub
status:
  loadBalancer: {}