#
# Minimum set of libs required by kernels and for basic data-science tasks
# Created to provide minimum conda environment for Kubernetes agents
#
channels: # should correspond with all .condarc files in repo & install.sh
  - jetbrains
  - jetbrains-dev
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12

  # libraries needed by evaluator
  - ipykernel=5.5.3
  - ipython_genutils=0.2.0

  # https://github.com/ipython/ipython/issues/12740
  - jedi=0.17.2

  # Data Science libraries
  - matplotlib-base=3.3.4
  - numpy=1.19.5
  - pandas=1.3.4

  - pip=21.3.1
  - boto3=1.17.7
  - pip:
    - lets-plot==2.3.0
