apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: datalore-on-premise-agents-config
    files:
      - configs/agents_config.yaml
  - name: datalore-on-premise-logback-config
    files:
      - configs/logback.xml
  - name: datalore-on-premise-plans-config
    files:
      - configs/plans_config.yaml
  - name: datalore-on-premise-envs
    files:
      - configs/envs/environment_minimal.yml
      - configs/envs/requirements_minimal.txt
  - name: datalore-on-premise-databases-configs
    files:
      - configs/connection_checker.yaml
      - configs/introspection.yaml
generatorOptions:
  disableNameSuffixHash: true

resources:
  - configs/user_config.yaml
  - configs/db_config.yaml
  - k8s.yaml

patchesStrategicMerge:
  - configs/images_config.yaml
  - configs/volumes_config.yaml
